- hosts: targets
  become: true
  gather_facts: false
  tasks:
    - name: Stop cluster
      command: pcs cluster stop --all
      run_once: true
      failed_when: false

    - name: Disable cluster at boot
      command: pcs cluster disable --all
      run_once: true
      failed_when: false

    - name: Destroy cluster configuration
      command: pcs cluster destroy --force
      run_once: true
      failed_when: false

